//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reisswolf.Desktop {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class ExportApi : global::System.Configuration.ApplicationSettingsBase {
        
        private static ExportApi defaultInstance = ((ExportApi)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ExportApi())));
        
        public static ExportApi Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://testauth.fibabanka.com.tr/v1/oauth/token?grant_type=client_credentials&sc" +
            "ope=v1.document-archive.savearchive:post")]
        public string AuthUrl {
            get {
                return ((string)(this["AuthUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://testapigw.fibabanka.com.tr/v1/document-archive/save-archive")]
        public string ServisUrl {
            get {
                return ((string)(this["ServisUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("658340d0-6031-4bf3-8622-6f60e4eb525f")]
        public string ClientId {
            get {
                return ((string)(this["ClientId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7f774c04-eb07-4498-9d4d-7e97efe0c40d")]
        public string ClientSecret {
            get {
                return ((string)(this["ClientSecret"]));
            }
        }
    }
}
