//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reisswolf.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIBAOutgoing
    {
        public int ID { get; set; }
        public string DocumentSerialNo { get; set; }
        public string NationalIdentityNo { get; set; }
        public string CompanyCode { get; set; }
        public string BarcodeCourrierArchiveNo { get; set; }
        public string ParcelCodeArchiveNo { get; set; }
        public bool IsScanned { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> SentTime { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Users CreatedByUser { get; set; }
        public virtual Users ModifiedByUser { get; set; }
    }
}
