//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reisswolf.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIBAIncome
    {
        public int ID { get; set; }
        public string DocumentSerialNo { get; set; }
        public string NationalIdentityNo { get; set; }
        public string CompanyCode { get; set; }
        public bool ItWillScanFlag { get; set; }
        public bool IsSuccessFlag { get; set; }
        public bool IsSent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
    }
}
